[package]
name = "saxtutor"
version = "0.1.0"
description = "Desktop saxophone learning app"
authors = ["an-bhv"]
edition = "2021"

[lib]
name = "saxtutor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-foundation = { version = "0.3", features = ["NSString", "NSValue", "NSObject"] }
